name: e-Motion-fe CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      # Chạy script "format:check" mới để kiểm tra Prettier
      - name: Check formatting with Prettier
        run: npm run format:check

      # Chạy script "lint" mới để kiểm tra lỗi code với ESLint
      - name: Check for code errors with ESLint
        run: npm run lint

      # Chạy script "test" mới với Vitest
      #- name: Run unit tests with Vitest
      #  run: npm run test

      # Chạy build
      - name: Build project
        run: npm run build
